name = "TradeLayer"
client_id = ""
application_url = "https://trade-layer.onrender.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_orders,read_customers"

[auth]
redirect_urls = [
  "https://trade-layer.onrender.com/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
