name = "TradeLayer"
client_id = "92ed0ed9f3e32ac2520b3586d04e0651"
application_url = "https://trade-layer.onrender.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_orders,read_customers"

[auth]
redirect_urls = [
  "https://trade-layer.onrender.com/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
